apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.15.0
  monitoring:
    metrics:
      elasticsearchRefs:
      - secretName: central-stack-mon-es-ref
    logs:
      elasticsearchRefs:
      - secretName: central-stack-mon-es-ref
  count: 1 # Count of Kibana replicas to create.
  elasticsearchRef:
    name: elasticsearch
  http:
    service:
      spec:
        type: LoadBalancer